WS_U2/Models/ErrorViewModel.cs
namespace WS_U2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WS_U2/Models/Post.cs
namespace WS_U2.Models
{
    public class Post
    {
        public int Id { get; set; }
        public Guid TopicId { get; set; }
        public string PostedBy { get; set; }
        public DateTime PostedDateTime { get; set; }
        public string PostBody { get; set; }
    }
}

WS_U2/Models/Topic.cs
using System.ComponentModel.DataAnnotations;

namespace WS_U2.Models
{
    public class Topic
    {
        public int Id { get; set; }
        public Guid TopicId { get; set; }

        [StringLength(75)]
        public string Title { get; set; }

        public string CreatedBy { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public DateTime LastPostDateTime { get; set; }
        public string PostBody { get; set; }
    }
}

WS_U2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using WS_U2.Models;

namespace WS_U2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            List<Topic> topicList = new();
            List<Topic> orderedList = new();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44375/api/topics"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    topicList = JsonConvert.DeserializeObject<List<Topic>>(apiResponse);
                }
            }

            orderedList = topicList.OrderByDescending(x => x.LastPostDateTime).ToList();

            return View(orderedList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WS_U2/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WS_U2.Models;
using WS_U2.Services;

namespace WS_U2.Controllers
{
    public class PostController : Controller
    {
        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("TopicId, PostBody")] Post post)
        {
            AESService aesService = new();
            Topic topic = new();

            using (var httpClient = new HttpClient())
            {
                post.PostedBy = aesService.GenerateEncryptedUsername(9);
                post.PostedDateTime = DateTime.Now;

                topic.LastPostDateTime = DateTime.Now;
                topic.TopicId = post.TopicId;

                var postPayload = new StringContent(JsonConvert.SerializeObject(post), Encoding.UTF8, "application/json");
                var topicPayload = new StringContent(JsonConvert.SerializeObject(topic), Encoding.UTF8, "application/json");
                await httpClient.PostAsync("https://localhost:44375/api/posts", postPayload);
                await httpClient.PatchAsync("https://localhost:44375/api/topics/" + post.TopicId, topicPayload);
            }

            return Redirect("/Home/Index");
        }
    }
}

WS_U2/Controllers/TopicController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using WS_U2.Models;
using WS_U2.Services;

namespace WS_U2.Controllers
{
    public class TopicController : Controller
    {
        // GET: TopicController/Details/5
        public async Task<ActionResult> View(int id)
        {
            Topic topic = new();
            List<Post> posts;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44375/api/topics/" + id))
                {
                    string topicResponse = await response.Content.ReadAsStringAsync();
                    topic = JsonConvert.DeserializeObject<Topic>(topicResponse);
                }

                using (var response = await httpClient.GetAsync("https://localhost:44375/api/posts/" + topic.TopicId))
                {
                    string postsResponse = await response.Content.ReadAsStringAsync();
                    posts = JsonConvert.DeserializeObject<List<Post>>(postsResponse);
                }
            }
            ViewBag.Posts = posts;
            return View(topic);
        }

        public ActionResult Cancel()
        {
            return Redirect("/Home/Index");
        }

        // GET: TopicController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TopicController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Title, PostBody")] Topic topic)
        {
            AESService aesService = new();
            topic.CreatedBy = aesService.GenerateEncryptedUsername(9);
            topic.CreatedDateTime = DateTime.Now;
            topic.LastPostDateTime = DateTime.Now;
            topic.TopicId = Guid.NewGuid();

            using (var httpClient = new HttpClient())
            {
                var topicPayload = new StringContent(JsonConvert.SerializeObject(topic), Encoding.UTF8, "application/json");
                await httpClient.PostAsync("https://localhost:44375/api/topics", topicPayload);
            }

            return Redirect("/Home/Index");
        }
    }
}

WS_U2/Views/Home/Index.cshtml
@using WS_U2.Models
@model List<Topic>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a asp-controller="Topic" asp-action="Create">New topic</a>
    @if (Model != null)
    {
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Created by</th>
                    <th scope="col">Created on</th>
                    <th scope="col">Last updated</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var topic in Model)
                {
                    <tr class="topic" onclick="location.href = '@Url.Action("View", "Topic", new { id = @topic.Id })'">
                        <th scope="row">@Html.Encode(topic.Title)</th>
                        <td>@topic.CreatedBy</td>
                        <td>@topic.CreatedDateTime.ToUniversalTime()</td>
                        <td>@topic.LastPostDateTime.ToUniversalTime()</td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WS_U2/Views/Shared/Components/NewPost/Default.cshtml
@model Post
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="mt-3">
    <h6>New post</h6>
    <div class="col-12">
        <form asp-controller="Post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(x => x.TopicId)
            <div class="form-group mt-3">
                @await Component.InvokeAsync("TextEditor", "PostBody")
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Post" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WS_U2/Views/Shared/Components/TextEditor/Default.cshtml
@model Post
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string bold = "<b></b>";
    string italics = "<i></i>";
    string underline = "<u></u>";
}

<div>
    <label asp-for="PostBody" name="PostBody" class="control-label" hidden="true"></label>
    <h6>Text</h6>
    <p>Allowed text tags: <b>@bold</b>, <i>@italics</i> and <u>@underline</u></p>
    <textarea asp-for="PostBody" name="PostBody" id="TextEditor" class="form-control"></textarea>
    <span asp-validation-for="PostBody" name="PostBody" class="text-danger"></span>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WS_U2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WS_U2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WS_U2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WS_U2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WS_U2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WS_U2/Views/Topic/Create.cshtml
@model WS_U2.Models.Topic

@{
    ViewData["Title"] = "Create";
}
<h4>New topic</h4>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <h6>Title</h6>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                @await Component.InvokeAsync("TextEditor", "PostBody")
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt-3">
    <a asp-action="Cancel">Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WS_U2/Views/Topic/View.cshtml
@using System.Web
@model Topic
@{
    ViewData["Title"] = @Model.Title;
}

<div>
    <div class="row">
    <div class="col-auto">
        @Html.Encode(Model.Title)
    </div>
    <div class="col-auto">
        @Model.CreatedBy
    </div>
    <div class="col-auto">
        @Model.CreatedDateTime
    </div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">
            @Html.Raw(EncodePost(Model.PostBody))
        </div>
    </div>
</div>

<h3>Comments</h3>
    @foreach (var post in ViewBag.Posts)
    {
        <div class="border-bottom mt-2">
            <div class="row">
                <div class="col-auto">
                    @post.PostedBy
                </div>
                <div class="col-auto">
                    @post.PostedDateTime
                </div>
            </div>
            <div class="row mt-2 mb-2">
                <div class="col">
                    @Html.Raw(EncodePost(post.PostBody))
                </div>
            </div>
        </div>
    }
    @await Component.InvokeAsync("NewPost", new { topicId = @Model.TopicId })
</p>

@{
    string EncodePost(string text)
    {
        var allowedTags = new List<string>() { "<b>","</b>", "<i>", "</i>", "<u>", "</u>"};
        if(!string.IsNullOrEmpty(text))
        {
            string encodedContent = HttpUtility.HtmlEncode(text);
            foreach (var tag in allowedTags)
            {
                string encodedTag = HttpUtility.HtmlEncode(tag);
                encodedContent = encodedContent.Replace(encodedTag, tag);
            }
            return encodedContent;
        }
        
        return null;
    }
}